[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-querystring"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[prune]
  go-tests = true
  unused-packages = true
